version: '3.1'
services:
    db:
        image: 'mysql:8.0'
        working_dir: /app
        container_name: db
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=ebs_test
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
        ports:
            - '61002:3306'
        networks:
            - ebs
    php-fpm:
        build:
            context: docker
            dockerfile: Dockerfile
        working_dir: /app
        container_name: php-fpm
        volumes:
            - '.:/app'
        ports:
            - "3000:8000"
        depends_on:
            - db
        links:
            - db
        networks:
            - ebs
networks:
    ebs:
        driver: bridge
